services:
  mysql:
    image: mysql:latest
    container_name: dbmsql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
    ports:
      - 3306:3306
    volumes:
      - db_data:/val/lib/mysql
volumes:
  db_data:
